# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class DataSaveLocationVendor(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, code_email: str=None, ip: str=None, id_prospect: int=None, latitude: float=None, longitude: float=None):  # noqa: E501
        """DataSaveLocationVendor - a model defined in Swagger

        :param code_email: The code_email of this DataSaveLocationVendor.  # noqa: E501
        :type code_email: str
        :param ip: The ip of this DataSaveLocationVendor.  # noqa: E501
        :type ip: str
        :param id_prospect: The id_prospect of this DataSaveLocationVendor.  # noqa: E501
        :type id_prospect: int
        :param latitude: The latitude of this DataSaveLocationVendor.  # noqa: E501
        :type latitude: float
        :param longitude: The longitude of this DataSaveLocationVendor.  # noqa: E501
        :type longitude: float
        """
        self.swagger_types = {
            'code_email': str,
            'ip': str,
            'id_prospect': int,
            'latitude': float,
            'longitude': float
        }

        self.attribute_map = {
            'code_email': 'code_email',
            'ip': 'ip',
            'id_prospect': 'id_prospect',
            'latitude': 'latitude',
            'longitude': 'longitude'
        }
        self._code_email = code_email
        self._ip = ip
        self._id_prospect = id_prospect
        self._latitude = latitude
        self._longitude = longitude

    @classmethod
    def from_dict(cls, dikt) -> 'DataSaveLocationVendor':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DataSaveLocationVendor of this DataSaveLocationVendor.  # noqa: E501
        :rtype: DataSaveLocationVendor
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code_email(self) -> str:
        """Gets the code_email of this DataSaveLocationVendor.


        :return: The code_email of this DataSaveLocationVendor.
        :rtype: str
        """
        return self._code_email

    @code_email.setter
    def code_email(self, code_email: str):
        """Sets the code_email of this DataSaveLocationVendor.


        :param code_email: The code_email of this DataSaveLocationVendor.
        :type code_email: str
        """

        self._code_email = code_email

    @property
    def ip(self) -> str:
        """Gets the ip of this DataSaveLocationVendor.


        :return: The ip of this DataSaveLocationVendor.
        :rtype: str
        """
        return self._ip

    @ip.setter
    def ip(self, ip: str):
        """Sets the ip of this DataSaveLocationVendor.


        :param ip: The ip of this DataSaveLocationVendor.
        :type ip: str
        """

        self._ip = ip

    @property
    def id_prospect(self) -> int:
        """Gets the id_prospect of this DataSaveLocationVendor.


        :return: The id_prospect of this DataSaveLocationVendor.
        :rtype: int
        """
        return self._id_prospect

    @id_prospect.setter
    def id_prospect(self, id_prospect: int):
        """Sets the id_prospect of this DataSaveLocationVendor.


        :param id_prospect: The id_prospect of this DataSaveLocationVendor.
        :type id_prospect: int
        """

        self._id_prospect = id_prospect

    @property
    def latitude(self) -> float:
        """Gets the latitude of this DataSaveLocationVendor.


        :return: The latitude of this DataSaveLocationVendor.
        :rtype: float
        """
        return self._latitude

    @latitude.setter
    def latitude(self, latitude: float):
        """Sets the latitude of this DataSaveLocationVendor.


        :param latitude: The latitude of this DataSaveLocationVendor.
        :type latitude: float
        """

        self._latitude = latitude

    @property
    def longitude(self) -> float:
        """Gets the longitude of this DataSaveLocationVendor.


        :return: The longitude of this DataSaveLocationVendor.
        :rtype: float
        """
        return self._longitude

    @longitude.setter
    def longitude(self, longitude: float):
        """Sets the longitude of this DataSaveLocationVendor.


        :param longitude: The longitude of this DataSaveLocationVendor.
        :type longitude: float
        """

        self._longitude = longitude
