# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.base_request import BaseRequest  # noqa: F401,E501
from swagger_server.models.customer_save_location_vendor import CustomerSaveLocationVendor  # noqa: F401,E501
from swagger_server import util


class RequestSaveLocationVendor(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, channel: str=None, external_transaction_id: str=None, customer: CustomerSaveLocationVendor=None):  # noqa: E501
        """RequestSaveLocationVendor - a model defined in Swagger

        :param channel: The channel of this RequestSaveLocationVendor.  # noqa: E501
        :type channel: str
        :param external_transaction_id: The external_transaction_id of this RequestSaveLocationVendor.  # noqa: E501
        :type external_transaction_id: str
        :param customer: The customer of this RequestSaveLocationVendor.  # noqa: E501
        :type customer: CustomerSaveLocationVendor
        """
        self.swagger_types = {
            'channel': str,
            'external_transaction_id': str,
            'customer': CustomerSaveLocationVendor
        }

        self.attribute_map = {
            'channel': 'channel',
            'external_transaction_id': 'externalTransactionId',
            'customer': 'customer'
        }
        self._channel = channel
        self._external_transaction_id = external_transaction_id
        self._customer = customer

    @classmethod
    def from_dict(cls, dikt) -> 'RequestSaveLocationVendor':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RequestSaveLocationVendor of this RequestSaveLocationVendor.  # noqa: E501
        :rtype: RequestSaveLocationVendor
        """
        return util.deserialize_model(dikt, cls)

    @property
    def channel(self) -> str:
        """Gets the channel of this RequestSaveLocationVendor.


        :return: The channel of this RequestSaveLocationVendor.
        :rtype: str
        """
        return self._channel

    @channel.setter
    def channel(self, channel: str):
        """Sets the channel of this RequestSaveLocationVendor.


        :param channel: The channel of this RequestSaveLocationVendor.
        :type channel: str
        """

        self._channel = channel

    @property
    def external_transaction_id(self) -> str:
        """Gets the external_transaction_id of this RequestSaveLocationVendor.


        :return: The external_transaction_id of this RequestSaveLocationVendor.
        :rtype: str
        """
        return self._external_transaction_id

    @external_transaction_id.setter
    def external_transaction_id(self, external_transaction_id: str):
        """Sets the external_transaction_id of this RequestSaveLocationVendor.


        :param external_transaction_id: The external_transaction_id of this RequestSaveLocationVendor.
        :type external_transaction_id: str
        """

        self._external_transaction_id = external_transaction_id

    @property
    def customer(self) -> CustomerSaveLocationVendor:
        """Gets the customer of this RequestSaveLocationVendor.


        :return: The customer of this RequestSaveLocationVendor.
        :rtype: CustomerSaveLocationVendor
        """
        return self._customer

    @customer.setter
    def customer(self, customer: CustomerSaveLocationVendor):
        """Sets the customer of this RequestSaveLocationVendor.


        :param customer: The customer of this RequestSaveLocationVendor.
        :type customer: CustomerSaveLocationVendor
        """

        self._customer = customer
