# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.base_response import BaseResponse  # noqa: F401,E501
from swagger_server.models.data_get_location import DataGetLocation  # noqa: F401,E501
from swagger_server import util


class ResponseGetLocation(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, channel: str=None, external_transaction_id: str=None, internal_transaction_id: str=None, code: str=None, message: str=None, data: DataGetLocation=None):  # noqa: E501
        """ResponseGetLocation - a model defined in Swagger

        :param channel: The channel of this ResponseGetLocation.  # noqa: E501
        :type channel: str
        :param external_transaction_id: The external_transaction_id of this ResponseGetLocation.  # noqa: E501
        :type external_transaction_id: str
        :param internal_transaction_id: The internal_transaction_id of this ResponseGetLocation.  # noqa: E501
        :type internal_transaction_id: str
        :param code: The code of this ResponseGetLocation.  # noqa: E501
        :type code: str
        :param message: The message of this ResponseGetLocation.  # noqa: E501
        :type message: str
        :param data: The data of this ResponseGetLocation.  # noqa: E501
        :type data: DataGetLocation
        """
        self.swagger_types = {
            'channel': str,
            'external_transaction_id': str,
            'internal_transaction_id': str,
            'code': str,
            'message': str,
            'data': DataGetLocation
        }

        self.attribute_map = {
            'channel': 'channel',
            'external_transaction_id': 'externalTransactionId',
            'internal_transaction_id': 'internalTransactionId',
            'code': 'code',
            'message': 'message',
            'data': 'data'
        }
        self._channel = channel
        self._external_transaction_id = external_transaction_id
        self._internal_transaction_id = internal_transaction_id
        self._code = code
        self._message = message
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'ResponseGetLocation':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ResponseGetLocation of this ResponseGetLocation.  # noqa: E501
        :rtype: ResponseGetLocation
        """
        return util.deserialize_model(dikt, cls)

    @property
    def channel(self) -> str:
        """Gets the channel of this ResponseGetLocation.


        :return: The channel of this ResponseGetLocation.
        :rtype: str
        """
        return self._channel

    @channel.setter
    def channel(self, channel: str):
        """Sets the channel of this ResponseGetLocation.


        :param channel: The channel of this ResponseGetLocation.
        :type channel: str
        """

        self._channel = channel

    @property
    def external_transaction_id(self) -> str:
        """Gets the external_transaction_id of this ResponseGetLocation.


        :return: The external_transaction_id of this ResponseGetLocation.
        :rtype: str
        """
        return self._external_transaction_id

    @external_transaction_id.setter
    def external_transaction_id(self, external_transaction_id: str):
        """Sets the external_transaction_id of this ResponseGetLocation.


        :param external_transaction_id: The external_transaction_id of this ResponseGetLocation.
        :type external_transaction_id: str
        """

        self._external_transaction_id = external_transaction_id

    @property
    def internal_transaction_id(self) -> str:
        """Gets the internal_transaction_id of this ResponseGetLocation.


        :return: The internal_transaction_id of this ResponseGetLocation.
        :rtype: str
        """
        return self._internal_transaction_id

    @internal_transaction_id.setter
    def internal_transaction_id(self, internal_transaction_id: str):
        """Sets the internal_transaction_id of this ResponseGetLocation.


        :param internal_transaction_id: The internal_transaction_id of this ResponseGetLocation.
        :type internal_transaction_id: str
        """

        self._internal_transaction_id = internal_transaction_id

    @property
    def code(self) -> str:
        """Gets the code of this ResponseGetLocation.


        :return: The code of this ResponseGetLocation.
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code: str):
        """Sets the code of this ResponseGetLocation.


        :param code: The code of this ResponseGetLocation.
        :type code: str
        """

        self._code = code

    @property
    def message(self) -> str:
        """Gets the message of this ResponseGetLocation.


        :return: The message of this ResponseGetLocation.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this ResponseGetLocation.


        :param message: The message of this ResponseGetLocation.
        :type message: str
        """

        self._message = message

    @property
    def data(self) -> DataGetLocation:
        """Gets the data of this ResponseGetLocation.


        :return: The data of this ResponseGetLocation.
        :rtype: DataGetLocation
        """
        return self._data

    @data.setter
    def data(self, data: DataGetLocation):
        """Sets the data of this ResponseGetLocation.


        :param data: The data of this ResponseGetLocation.
        :type data: DataGetLocation
        """

        self._data = data
